const FLEET_URL='https://velocidades.seguimos.cl/?all-buses-data=1';
const TARGET_ROUTE='411';
const WORK={lat:-33.42548,lon:-70.61380,name:'Metro Pedro de Valdivia'};
const HOME={lat:-33.39477,lon:-70.56152,name:'Kennedy · Gerónimo de Alderete'};
const ARRIVAL_KM=.35;
const $=id=>document.getElementById(id);let lastFetch=0,cache=null,timer=null,currentProgress=null,celebrating=false,trackedPlate='';
function cleanPlate(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}
function routeIs411(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').includes(TARGET_ROUTE)}
function age(ts){const s=Math.max(0,Math.round((Date.now()-ts)/1000));return s<60?`${s}s`:`${Math.round(s/60)} min`}
function distance(a,b){const R=6371,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lon-a.lon),q=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function progressFor(bus){const total=distance(WORK,HOME),fromWork=distance(WORK,bus),toHome=distance(bus,HOME);let p=(fromWork*fromWork+total*total-toHome*toHome)/(2*total*total);return Math.max(0,Math.min(1,p))}
function parse(json){return ((json?.geojson||json)?.features||[]).map(f=>{const p=f.properties||{},c=f.geometry?.coordinates||[],lat=+c[1],lon=+c[0],ts=Date.parse(p.timestamp);return{plate:cleanPlate(p.license_plate),route:String(p.route_code||''),lat,lon,ts,speed:Number.isFinite(+p.speed)?+p.speed:null}}).filter(b=>Number.isFinite(b.lat)&&Number.isFinite(b.lon)&&Number.isFinite(b.ts))}
async function fleet(){if(cache&&Date.now()-lastFetch<55000)return cache;const c=new AbortController(),t=setTimeout(()=>c.abort(),18000);try{const r=await fetch(FLEET_URL,{signal:c.signal,credentials:'omit'});if(!r.ok)throw Error();cache=parse(await r.json());lastFetch=Date.now();return cache}finally{clearTimeout(t)}}
function candidate(b){const p=progressFor(b),corridor=distance(b,{lat:WORK.lat+(HOME.lat-WORK.lat)*p,lon:WORK.lon+(HOME.lon-WORK.lon)*p});return{...b,p,corridor,toHome:distance(b,HOME)}}
function findTracked(buses){const exact=buses.find(b=>b.plate===trackedPlate);return exact?candidate(exact):null}
function pathPoint(p){const path=$('routePath'),len=path.getTotalLength(),pt=path.getPointAtLength(len*Math.max(0,Math.min(1,p))),svg=path.ownerSVGElement,r=svg.getBoundingClientRect(),vb=svg.viewBox.baseVal;return{x:r.left+(pt.x-vb.x)/vb.width*r.width,y:r.top+(pt.y-vb.y)/vb.height*r.height}}
function moveBus(p,animate=true){currentProgress=p;const bus=$('bus'),journey=document.querySelector('.journey'),jr=journey.getBoundingClientRect(),pt=pathPoint(p);if(!animate)bus.style.transition='none';bus.style.left=`${pt.x-jr.left}px`;bus.style.top=`${pt.y-jr.top}px`;bus.classList.remove('hidden');if(!animate)requestAnimationFrame(()=>bus.style.transition='left 1.6s cubic-bezier(.22,1,.36,1),top 1.6s cubic-bezier(.22,1,.36,1)')}
function makeConfetti(){const box=document.querySelector('.confetti');if(box.children.length)return;for(let i=0;i<70;i++){const s=document.createElement('i');s.style.setProperty('--x',`${Math.random()*100}%`);s.style.setProperty('--d',`${2.8+Math.random()*3.8}s`);s.style.setProperty('--delay',`${-Math.random()*5}s`);s.style.setProperty('--r',`${Math.random()*720-360}deg`);s.style.setProperty('--h',`${Math.floor(Math.random()*360)}`);box.appendChild(s)}}
function celebrate(){if(celebrating)return;celebrating=true;makeConfetti();document.body.classList.add('arrived');$('arrivalCelebration').classList.remove('hidden')}
function stopCelebration(){if(!celebrating)return;celebrating=false;document.body.classList.remove('arrived');$('arrivalCelebration').classList.add('hidden')}
function render(bus){const arrived=bus.toHome<=ARRIVAL_KM||bus.p>=.97,p=arrived?1:bus.p,pct=arrived?100:Math.round(bus.p*100);moveBus(p);$('progressFill').style.width=`${pct}%`;$('percent').textContent=`${pct}%`;$('plate').textContent=bus.plate;$('speed').textContent=bus.speed===null?'Velocidad —':`${Math.round(bus.speed)} km/h`;$('age').textContent=`GPS ${age(bus.ts)}`;$('details').classList.remove('hidden');$('trackingLabel').textContent=`411 · ${bus.plate}`;let h='Forestín va camino a casa',m='Estamos siguiendo solamente esta micro.';if(!routeIs411(bus.route)){h='Encontramos la patente';m=`La patente ${bus.plate} aparece en vivo, pero ahora figura como servicio ${bus.route||'sin servicio identificado'}, no como 411.`;stopCelebration()}else if(bus.corridor>=3){h='Forestín está fuera del camino';m='Encontramos la micro, pero su GPS está lejos del trayecto entre Trabajo y Casa.';stopCelebration()}else if(arrived){h='¡Forestín llegó a casa!';m='¡Llegó! Forestín ya está en casa.';celebrate()}else{stopCelebration();if(bus.p<.12){h='Forestín está cerca del trabajo';m='La micro está al comienzo del camino.'}else if(bus.p>.82){h='¡Forestín ya está cerquita!';m='La 411 está llegando a casa.'}else if(bus.p>.5){h='Forestín pasó la mitad';m='¡Ya queda menos para llegar a casa!'}}$('headline').textContent=h;$('message').textContent=m}
function plateNotFound(){stopCelebration();$('headline').textContent='No encontramos esa patente';$('message').textContent=`No aparece ${trackedPlate} en la señal GPS actual. Revisa la patente o vuelve a intentar en un minuto.`;$('trackingLabel').textContent=`BUSCANDO · ${trackedPlate}`;$('percent').textContent='—';$('progressFill').style.width='0';$('bus').classList.add('hidden');$('details').classList.add('hidden');currentProgress=null}
async function refresh(){if(!trackedPlate)return;const btn=$('refresh');btn.disabled=true;btn.textContent='Buscando…';try{const buses=await fleet(),bus=findTracked(buses);bus?render(bus):plateNotFound()}catch{$('headline').textContent='No pudimos mirar el camino';$('message').textContent='La señal de las micros no respondió. Intenta de nuevo en un momento.'}finally{btn.disabled=false;btn.textContent='Actualizar'}}
async function startTracking(raw){const plate=cleanPlate(raw),error=$('plateError');error.classList.add('hidden');if(plate.length<5||plate.length>6){error.textContent='Revisa la patente. Por ejemplo: ABCD12.';error.classList.remove('hidden');return}trackedPlate=plate;$('plateInput').value=plate;$('plateSearch').disabled=true;$('plateSearch').textContent='Buscando…';lastFetch=0;try{const buses=await fleet(),bus=findTracked(buses);if(!bus){error.textContent=`No encontramos ${plate} en la señal GPS actual. Revisa la patente o intenta nuevamente.`;error.classList.remove('hidden');trackedPlate='';return}$('plateGate').classList.add('hidden');$('mainScene').classList.remove('locked');render(bus);if(timer)clearInterval(timer);timer=setInterval(refresh,60000)}catch{error.textContent='No pudimos consultar las micros ahora. Intenta nuevamente.';error.classList.remove('hidden');trackedPlate=''}finally{$('plateSearch').disabled=false;$('plateSearch').textContent='Buscar'}}
function changePlate(){stopCelebration();trackedPlate='';currentProgress=null;if(timer){clearInterval(timer);timer=null}$('bus').classList.add('hidden');$('details').classList.add('hidden');$('progressFill').style.width='0';$('percent').textContent='—';$('mainScene').classList.add('locked');$('plateGate').classList.remove('hidden');$('plateInput').focus()}
$('plateInput').addEventListener('input',e=>{const pos=e.target.selectionStart;e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9 -]/g,'');try{e.target.setSelectionRange(pos,pos)}catch{}});
$('plateForm').addEventListener('submit',e=>{e.preventDefault();startTracking($('plateInput').value)});
$('refresh').addEventListener('click',()=>{lastFetch=0;refresh()});$('changePlate').addEventListener('click',changePlate);window.addEventListener('resize',()=>{if(currentProgress!==null)moveBus(currentProgress,false)});setTimeout(()=>$('plateInput').focus(),350);