const FLEET_URL='https://velocidades.seguimos.cl/?all-buses-data=1';
const TARGET_ROUTE='411';
const WORK={lat:-33.42548,lon:-70.61380,name:'Metro Pedro de Valdivia'};
const HOME={lat:-33.39477,lon:-70.56152,name:'Kennedy · Gerónimo de Alderete'};
const ARRIVAL_KM=.35;
const $=id=>document.getElementById(id);let lastFetch=0,cache=null,timer=null,currentProgress=null,celebrating=false;
function routeIs411(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').includes(TARGET_ROUTE)}
function age(ts){const s=Math.max(0,Math.round((Date.now()-ts)/1000));return s<60?`${s}s`:`${Math.round(s/60)} min`}
function distance(a,b){const R=6371,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lon-a.lon),q=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function progressFor(bus){const total=distance(WORK,HOME),fromWork=distance(WORK,bus),toHome=distance(bus,HOME);let p=(fromWork*fromWork+total*total-toHome*toHome)/(2*total*total);return Math.max(0,Math.min(1,p))}
function parse(json){return ((json?.geojson||json)?.features||[]).map(f=>{const p=f.properties||{},c=f.geometry?.coordinates||[],lat=+c[1],lon=+c[0],ts=Date.parse(p.timestamp);return{plate:String(p.license_plate||'').toUpperCase(),route:String(p.route_code||''),lat,lon,ts,speed:Number.isFinite(+p.speed)?+p.speed:null}}).filter(b=>routeIs411(b.route)&&Number.isFinite(b.lat)&&Number.isFinite(b.lon)&&Number.isFinite(b.ts))}
async function fleet(){if(cache&&Date.now()-lastFetch<55000)return cache;const c=new AbortController(),t=setTimeout(()=>c.abort(),18000);try{const r=await fetch(FLEET_URL,{signal:c.signal,credentials:'omit'});if(!r.ok)throw Error();cache=parse(await r.json());lastFetch=Date.now();return cache}finally{clearTimeout(t)}}
function candidate(b){const p=progressFor(b),corridor=distance(b,{lat:WORK.lat+(HOME.lat-WORK.lat)*p,lon:WORK.lon+(HOME.lon-WORK.lon)*p});return{...b,p,corridor,toHome:distance(b,HOME)}}
function choose(buses){return buses.map(candidate).filter(b=>b.corridor<3&&b.p>=0&&b.p<=1).sort((a,b)=>b.p-a.p)[0]||null}
function pathPoint(p){const path=$('routePath'),len=path.getTotalLength(),pt=path.getPointAtLength(len*Math.max(0,Math.min(1,p))),svg=path.ownerSVGElement,r=svg.getBoundingClientRect(),vb=svg.viewBox.baseVal;return{x:r.left+(pt.x-vb.x)/vb.width*r.width,y:r.top+(pt.y-vb.y)/vb.height*r.height}}
function moveBus(p,animate=true){currentProgress=p;const bus=$('bus'),journey=document.querySelector('.journey'),jr=journey.getBoundingClientRect(),pt=pathPoint(p);if(!animate)bus.style.transition='none';bus.style.left=`${pt.x-jr.left}px`;bus.style.top=`${pt.y-jr.top}px`;bus.classList.remove('hidden');if(!animate)requestAnimationFrame(()=>bus.style.transition='left 1.6s cubic-bezier(.22,1,.36,1),top 1.6s cubic-bezier(.22,1,.36,1)')}
function makeConfetti(){const box=document.querySelector('.confetti');if(box.children.length)return;for(let i=0;i<70;i++){const s=document.createElement('i');s.style.setProperty('--x',`${Math.random()*100}%`);s.style.setProperty('--d',`${2.8+Math.random()*3.8}s`);s.style.setProperty('--delay',`${-Math.random()*5}s`);s.style.setProperty('--r',`${Math.random()*720-360}deg`);s.style.setProperty('--h',`${Math.floor(Math.random()*360)}`);box.appendChild(s)}}
function celebrate(){if(celebrating)return;celebrating=true;makeConfetti();document.body.classList.add('arrived');$('arrivalCelebration').classList.remove('hidden')}
function stopCelebration(){if(!celebrating)return;celebrating=false;document.body.classList.remove('arrived');$('arrivalCelebration').classList.add('hidden')}
function render(bus){const arrived=bus.toHome<=ARRIVAL_KM||bus.p>=.97,p=arrived?1:bus.p,pct=arrived?100:Math.round(bus.p*100);moveBus(p);$('progressFill').style.width=`${pct}%`;$('percent').textContent=`${pct}%`;$('plate').textContent=bus.plate||'411';$('speed').textContent=bus.speed===null?'Velocidad —':`${Math.round(bus.speed)} km/h`;$('age').textContent=`GPS ${age(bus.ts)}`;$('details').classList.remove('hidden');let h='Forestín va camino a casa',m='Mira cómo la 411 avanza por el camino hacia casa.';if(arrived){h='¡Forestín llegó a casa!';m='¡Llegó! Forestín ya está en casa.';celebrate()}else{stopCelebration();if(bus.p<.12){h='¡Forestín recién salió!';m='La 411 está cerquita del trabajo.'}else if(bus.p>.82){h='¡Forestín ya está cerquita!';m='La 411 está llegando a casa.'}else if(bus.p>.5){h='Forestín pasó la mitad';m='¡Ya queda menos para llegar a casa!'}}$('headline').textContent=h;$('message').textContent=m}
function noBus(){stopCelebration();$('headline').textContent='Forestín todavía no aparece';$('message').textContent='No vemos una 411 en el camino entre Trabajo y Casa en este momento. Volveremos a mirar pronto.';$('percent').textContent='—';$('progressFill').style.width='0';$('bus').classList.add('hidden');$('details').classList.add('hidden');currentProgress=null}
async function refresh(){const btn=$('refresh');btn.disabled=true;btn.textContent='Buscando…';try{const buses=await fleet(),bus=choose(buses);bus?render(bus):noBus()}catch{$('headline').textContent='No pudimos mirar el camino';$('message').textContent='La señal de las micros no respondió. Intenta de nuevo en un momento.'}finally{btn.disabled=false;btn.textContent='Actualizar'}}
$('refresh').addEventListener('click',()=>{lastFetch=0;refresh()});window.addEventListener('resize',()=>{if(currentProgress!==null)moveBus(currentProgress,false)});refresh();timer=setInterval(refresh,60000);